url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: biodatageeks
email: your-email@domain.com
description: "Bioinformatics research team at Warsaw University of Technology"


# Team names, titles and social links
people:
- name: Tomasz 
  pic: 1
  position: Team Leader
  social:
    - title: twitter
      url: https://twitter.com/GambinTomasz
    - title: linkedin
      url: https://pl.linkedin.com/in/tomasz-gambin-a763253

- name: Marek 
  pic: 2
  position: Technology Leader
  social:
    - title: twitter
      url: https://twitter.com/MarekWiewiorka
    - title: linkedin
      url: https://pl.linkedin.com/in/marekwiewiorka

- name: Anastasia 
  pic: 3
  position: Reasercher, Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: https://pl.linkedin.com/in/ahryhorzhevska

- name: Agnieszka 
  pic: 4
  position: Reasercher, Developer
  social:
    - title: twitter
      url: https://twitter.com/agaszmurlo
    - title: linkedin
      url: https://pl.linkedin.com/in/abelkiewicz

- name: Wiktor 
  pic: 5
  position: Reasercher, Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/biodatageeks
  - title: github
    url: https://github.com/ZSIBio

# Postal address (add as many lines as necessary)
address:
  - line: Wydział Elektroniki Politechniki Warszawskiej, Instytut Informatyki
  - line: Nowowiejska 15/19, 00-665 Warszawa

# Build settings
markdown: kramdown
permalink: pretty